DROP DATABASE IF EXISTS recipebox;
CREATE DATABASE recipebox;

USE `recipebox`;

CREATE TABLE recipes(
    id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    recipe_name VARCHAR (50) NOT NULL,
    protein VARCHAR (30) NOT NULL,
    ingredient1 VARCHAR (30) NOT NULL,
    ingredient2 VARCHAR(30) NOT NULL,
    ingredient3 VARCHAR(30) NOT NULL,
    ingredient4 VARCHAR(30) NOT NULL,
    ingredient5 VARCHAR(30) NOT NULL,
    photo VARCHAR(200)NOT NULL
);
CREATE TABLE fridge(
    id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    item_name VARCHAR (50) NOT NULL,
    amount INTEGER NOT NULL
);
CREATE TABLE pantry(
    id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    item_name VARCHAR (50) NOT NULL,
    amount INTEGER NOT NULL
);
CREATE TABLE shoppinglist(
    id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    item_name VARCHAR (50) NOT NULL,
    amount INTEGER NOT NULL
);


DROP DATABASE IF EXISTS testdb;
CREATE DATABASE testdb;